routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\Admin\AdminController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\UserDetailController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\User\LoginLogController;
use App\Http\Controllers\Loan\LoanController;
use App\Http\Controllers\Loan\CreditCheckController;
use App\Http\Controllers\Loan\FolderController;
use App\Http\Controllers\Loan\UploadController;
use App\Http\Controllers\Offer\StatusController;
use App\Http\Controllers\Offer\OfferController;
use App\Http\Controllers\Loan\DefaulterController;
use App\Http\Controllers\Loan\RepaymentController;
use App\Http\Controllers\Loan\CommentController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\SupportResponseController;
use App\Http\Controllers\Report\CustomerBaseController;
use App\Http\Controllers\Report\LoanReportController;
use App\Http\Controllers\Report\LoanProcessController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "is_admin" middleware group. Now create something great!
|
*/

Route::get('/', function(){
	return redirect()->route('admin.home');
});

Route::group(['middleware'=>['is_admin']], function(){
	Route::get('/dashboard', [AdminController::class , 'home'])->name('admin.home');

	Route::resource('users', UserController::class)->except(['edit', 'update']);
	Route::resource('userDetails', UserDetailController::class)->only(['destroy']);
	Route::get('/users/perm/{id}', [UserController::class, 'perm']);
	Route::get('/platform/users/{type}', [UserController::class, 'custom_index']);
	Route::get('/transactions/user/{id}', [TransactionController::class, 'user_transactions']);
	Route::get('/loginLogs/user/{id}', [LoginLogController::class, 'user_login_logs']);

	Route::get('/loans/get/{type}', [LoanController::class, 'custom_index']);
	Route::resource('loans', LoanController::class)->only(['show']);
	Route::get('loans/{action}/{id}', [LoanController::class, 'action']);
	Route::get('loans/return/back/{id}', [LoanController::class, 'returnBack']);
	Route::get('credit_checks/create/{id}', [CreditCheckController::class, 'create_admin']);
	Route::resource('folders', FolderController::class)->only(['index', 'show']);
	Route::get('/folders/create/{id}', [FolderController::class, 'create_admin']);
	Route::get('/folders/show/{id}', [FolderController::class, 'show_main']);
	Route::post('/applications/uploads', [UploadController::class, 'create']);
	Route::resource('uploads', UploadController::class)->only(['destroy']);
	Route::get('/uploads/restore/{id}', [UploadController::class, 'restore']);
	Route::get('/trash', [UploadController::class, 'trash']);
	Route::get('/offers/create/{id}', [OfferController::class, 'createNew']);
	Route::resource('offers', OfferController::class)->only(['edit', 'update', 'show']);
	Route::post('/offers/store', [OfferController::class, 'store'])->name('createOffers');
	Route::get('/payout/loans/{id}', [LoanController::class, 'disburse']);
	Route::get('/defaulters/clear/{id}', [DefaulterController::class, 'clear']);
	Route::get('/repayments/update/user/{id}', [RepaymentController::class, 'updatePayments']);
	Route::resource('repayments', RepaymentController::class);
	Route::get('/comments/create/{id}', [CommentController::class, 'add']);
	Route::resource('comments', CommentController::class)->only(['index', 'store', 'show']);
	Route::resource('referrals', ReferralController::class)->only(['index']);

	Route::get('staff', [UserController::class, 'staff']);
	Route::get('staff/add', [UserController::class, 'new_staff']);
	Route::post('staff/add', [UserController::class, 'new_staff_post']);
	Route::get('staff/edit/{id}', [UserController::class, 'edit']);
	Route::post('staff/edit/{id}', [UserController::class, 'update']);
	Route::resource('transactions', TransactionController::class)->only(['index']);
	Route::resource('supportResponses', SupportResponseController::class)->except(['destroy', 'update', 'edit']);
	Route::get('/support/close/{id}', [SupportResponseController::class, 'closeSupport']);

	Route::get('/reports/customer-base', CustomerBaseController::class);
	Route::get('/reports/customer-base-generate', [CustomerBaseController::class, 'generate']);

	Route::get('/reports/loan-reports', LoanReportController::class);
	Route::get('/reports/loan-reports-generate', [LoanReportController::class, 'generate']);

	Route::get('/reports/loan-process', LoanProcessController::class);
	Route::get('/reports/loan-process-generate', [LoanProcessController::class, 'generate']);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\UserDetailController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\WalletController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\User\ChangePasswordController;
use App\Http\Controllers\User\AccountSecurityController;
use App\Http\Controllers\User\NotificationController;
use App\Http\Controllers\Transaction\CardController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\Loan\LoanController;
use App\Http\Controllers\Loan\CreditCheckController;
use App\Http\Controllers\Loan\RepaymentController;
use App\Http\Controllers\Offer\SignatureController;
use App\Http\Controllers\Offer\OfferController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\SupportResponseController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register'=>false, 'verify'=>true]);
Route::get('/migrate-my-db', function(){
	Artisan::call('migrate:fresh', [
	   '--force' => true, '--seed' => true
	]);
});

Route::group(['middleware'=>['auth','verified','is_user']], function(){
	/**Kyc Routes **/
	Route::get('/application', [UserDetailController::class, 'kyc']);
	Route::get('/application/preview', [UserDetailController::class, 'preview']);
	Route::group(['prefix'=>'application', 'middleware'=>'is_completed'], function() {
		Route::resource('kyc', UserDetailController::class)->only(['create', 'store']);
		Route::resource('pin', AccountSecurityController::class)->only(['create', 'store']);
		Route::get('/card/create', [CardController::class, 'initiateCardLink']);
		Route::get('/card/verify', [CardController::class, 'verifyPayment']);
	});
	/**Kyc Routes ends**/
	Route::group(['middleware'=>'is_complete'], function(){
		Route::get('/dashboard', [UserController::class, 'home'])->name('home');
		Route::resource('transactions', TransactionController::class)->only('index');
		Route::resource('loans', LoanController::class)->except(['edit', 'update']);
		Route::get('/credit-checks', [CreditCheckController::class, 'initiatePayment']);
		Route::get('/credit-checks/create', [CreditCheckController::class, 'create']);
		Route::resource('offers', OfferController::class)->only(['show']);
		Route::get('/loans/offer/sign/{id}', [OfferController::class, 'sign']);
		Route::resource('signatures', SignatureController::class)->only(['store']);
		Route::get('/repayments/from-wallet', [RepaymentController::class, 'payFromWallet']);
		Route::get('/repayments/from-card', [RepaymentController::class, 'initiateCardLink']);
		Route::get('/repayments/from-card/confirm', [RepaymentController::class, 'payFromCardConfirm']);

		Route::get('/profile', [UserController::class, 'profile']);
		Route::get('/security', [UserController::class, 'security']);
		Route::get('/notifications-settings', [UserController::class, 'notificationSetting']);
		Route::post('/notifications-settings', [UserController::class, 'notificationSettingPost'])->name('settings');
		Route::post('/security', [UserController::class, 'securityPost'])->name('secure_setting');
		Route::post('change-password', [ChangePasswordController::class, 'store'])->name('change.password');
		Route::get('/change-password', [ChangePasswordController::class, 'index']);

		Route::resource('referrals', ReferralController::class)->only(['index']);


		Route::group(['prefix'=>'wallet'], function(){
			Route::get('/', [WalletController::class, 'index']);
			Route::get('/deposit', [WalletController::class, 'deposit']);
			Route::post('/deposit', [WalletController::class, 'depositPost']);
			Route::get('/deposit/confirm', [WalletController::class, 'confirmDeposit']);
			Route::get('/withdraw', [WalletController::class, 'withdraw']);
			Route::post('/withdraw', [WalletController::class, 'withdrawPost']);
		});

		Route::resource('supports', SupportController::class)->except(['destroy', 'update', 'edit']);
		Route::resource('supportResponses', SupportResponseController::class)->except(['destroy', 'update', 'edit']);
		Route::get('/support/close/{id}', [SupportController::class, 'closeSupport']);

		Route::group(['prefix'=>'notifications'], function(){
			Route::get('/view/{id}', [NotificationController::class, 'view']);
			Route::get('/read_all', [NotificationController::class, 'read']);
		});

		Route::get('clear-loan/{id}', [LoanController::class, 'clearLoan']);
	});
	
});

Route::group(['middleware'=>'guest'], function(){
	Route::get('/', function(){
		return redirect()->route('home');
	});

	Route::group(['prefix'=>'auth'], function(){
		Route::get('register', [UserController::class, 'create'])->name('user.create');
		Route::post('register', [UserController::class, 'store'])->name('user.create');
	});
});


Route::get('/verify_referee/{ref}', [UserController::class, 'verify_referee'])->name('verify.referee');
Route::get('/charts', [ReferralController::class, 'userChart'])->name('referral.chart');
Route::post('/save-passport', [UserDetailController::class, 'savePassport']);
Route::post('/save-id', [UserDetailController::class, 'saveID']);
Route::post('/save-company-id', [UserDetailController::class, 'saveCompanyID']);
Route::get('/check-uploads', [UserDetailController::class, 'checkUploads']);
Route::get('/check-bvn/{bvn}/{phone}', [UserDetailController::class, 'getBvn']);
Route::get('/check-bank/{bank}/{account}', [UserDetailController::class, 'getBank']);
Route::post('/save-employment-letter', [LoanController::class, 'saveEmployment']);
Route::post('/save-utility-bill', [LoanController::class, 'saveUtility']);
Route::post('/save-statements', [LoanController::class, 'saveStatements']);
Route::post('/pin/validate', [AccountSecurityController::class, 'validatePin']);

app/Http/Controllers/SupportController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SupportRequest;
use App\Http\Resources\SupportResource;
use App\Interfaces\SupportInterface;
use Shamaseen\Repository\Generator\Utility\Controller;

/**
 * Class SupportController
 * @package App\Http\Controllers
 * @property-read SupportInterface $interface
 */
class SupportController extends Controller
{

    protected $routeIndex = 'supports';

    protected $pageTitle = 'Support';
    protected $createRoute = 'supports.create';

    protected $viewIndex = 'supports.index';
    protected $viewCreate = 'supports.create';
    protected $viewEdit = 'supports.edit';
    protected $viewShow = 'supports.show';

    /**
     * SupportController constructor.
     * @param SupportInterface $interface
     * @param SupportRequest $request
     * @param SupportResource $resource
     */
    public function __construct(SupportInterface $interface, SupportRequest $request)
    {
        parent::__construct($interface, $request, new  SupportResource([]));
        $this->middleware('role:user|support|super admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->interface->index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->interface->create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        return $this->interface->store();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $this->interface->show($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return parent::edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id)
    {
        return parent::update($id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        return parent::destroy($id);
    }

    public function closeSupport($id)
    {
        return $this->interface->closeSupport($id);
    }
}

resources/views/supports/create.blade.php
@php
use App\Http\Controllers\GlobalMethods as SuperM;
@endphp

@extends('layouts.user.app')

@section('title', __('Create new ticket'))

@section('content')
<div class="nk-content-inner">
	<div class="nk-content-body">
		<div class="components-preview wide-md mx-auto">
			<div class="nk-block nk-block-lg">
				<div class="nk-block-head">
					<div class="nk-block-head-content">
						<h4 class="title nk-block-title">Create new support tickets</h4>
						<div class="nk-block-des">
							<p>If you need solutions or support guidance, you can submit a ticket by selecting the appropriate department below.</p>
						</div>
					</div>
				</div>
				<form action="{{ route('supports.store') }}" method="post">
					@csrf
					<div class="card card-bordered">
						<div class="card-inner">
							<div class="card-head">
								<h5 class="card-title">Ticket Information</h5>
							</div>
							<div class="row g-4">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-label">Name</label>
										<div class="form-control-wrap">
											<input type="text" class="form-control" value="{{ $user->getFullname() }}" readonly="true">
										</div>
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-label">Email address</label>
										<div class="form-control-wrap">
											<input type="text" class="form-control" value="{{ $user->email }}" readonly="true">
										</div>
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-label">Department</label>
										<div class="form-control-wrap">
											<select class="form-control" name="department">
												<option>Marketing Department</option>
												<option>Transaction Department</option>
												<option>Risk Deparment</option>
												<option>Technical Deparment</option>
												<option>Abuse Deparment</option>
											</select>
										</div>
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-label">Priority</label>
										<div class="form-control-wrap">
											<select class="form-control" name="priority">
												<option>High</option>
												<option>Medium</option>
												<option>Low</option>
											</select>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="card card-bordered">
						<div class="card-inner">
							<div class="card-head">
								<h5 class="card-title">Message</h5>
							</div>
							<div class="row g-4">
								<div class="col-lg-12">
									<div class="form-group">
										<label class="form-label">Subject</label>
										<div class="form-control-wrap">
											<input type="text" class="form-control" name="subject" required="true">
										</div>
									</div>
								</div>
								<div class="col-lg-12">
									<div class="form-group">
										<label class="form-label">Message</label>
										<div class="form-control-wrap">
											<textarea class="summernote-basic" name="message"></textarea>
										</div>
									</div>
								</div>
								<div class="col-12">
									<div class="form-group">
										<button type="submit" class="btn btn-lg btn-primary">Submit</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

@push('more-scripts')
<link rel="stylesheet" href="{{ asset('assets/css/editors/summernote.css') }}">
<script src="{{ asset('assets/js/libs/editors/summernote.js') }}"></script>
<script src="{{ asset('assets/js/editors.js') }}"></script>
@endpush

resources/views/supports/edit.blade.php
@extends('layouts.app')

@section('content')



@endsection

resources/views/supports/index.blade.php
@extends('layouts.user.app')

@section('title', __('My Tickets'))

@section('content')
<div class="nk-content-inner">
	<div class="nk-content-body">
		<div class="components-preview wide-md mx-auto">
			<div class="nk-block-head nk-block-head-lg wide-sm">
				<div class="nk-block-head-content">
					<div class="nk-block-head-sub"><a class="back-to" href="{{ url()->previous() }}"><em class="icon ni ni-arrow-left"></em><span>Back</span></a></div>
					<h2 class="nk-block-title fw-normal">My Tickets</h2>
					<div class="nk-block-des">
						<p class="lead">Here are the list of all your tickets.</p>
					</div>
				</div>
			</div>
			<div class="nk-block nk-block-lg">
				<div class="card card-preview">
					<div class="card-inner">
						<table class="datatable-init nowrap nk-tb-list nk-tb-ulist" data-auto-responsive="false">
							<thead>
								<tr class="nk-tb-item nk-tb-head">
									<th class="nk-tb-col tb-col-mb"><span class="sub-text">TID</span></th>
									<th class="nk-tb-col tb-col-mb"><span class="sub-text">Department</span></th>
									<th class="nk-tb-col tb-col-md"><span class="sub-text">Subject</span></th>
									<th class="nk-tb-col tb-col-lg"><span class="sub-text">Status</span></th>
									<th class="nk-tb-col tb-col-md"><span class="sub-text">Last Updated</span></th>
									<th class="nk-tb-col nk-tb-col-tools text-right"></th>
								</tr>
							</thead>
							<tbody>
								@foreach($supports as $support)
								<tr class="nk-tb-item">
									<td class="nk-tb-col tb-col-mb">
										<span>{{ $support->id() }}</span>
									</td>
									<td class="nk-tb-col tb-col-mb">
										<span>{{ $support->department }}</span>
									</td>
									<td class="nk-tb-col tb-col-md">
										<span class="text-muted">{{ $support->subject }}</span>
									</td>
									<td class="nk-tb-col tb-col-md">
										@if($support->status == 'opened')
										<span class="badge badge-sm badge-dot has-bg badge-success d-mb-inline-flex">Opened</span>
										@else
										<span class="badge badge-sm badge-dot has-bg badge-danger d-mb-inline-flex">Closed</span>
										@endif
									</td>
									<td class="nk-tb-col tb-col-md">
										@if($support->responses()->count() > 0)
										<span class="text-muted">{{ date('M d, Y h:i A', strtotime($support->responses()->latest()->first()->created_at)) }}</span>
										@else
										<span class="text-muted">{{ date('M d, Y h:i A', strtotime($support->created_at)) }}</span>
										@endif
									</td>
									<td class="nk-tb-col nk-tb-col-tools">
										<ul class="nk-tb-actions gx-1">
											<li>
												<div class="drodown">
													<a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
													<div class="dropdown-menu dropdown-menu-right">
														<ul class="link-list-opt no-bdr">
															<li><a href="/supports/{{ $support->uuid() }}"><em class="icon ni ni-eye"></em><span>View Ticket</span></a></li>
															@if($support->status == 'opened')
															<li><a href="/support/close/{{ $support->uuid() }}"><em class="icon ni ni-focus"></em><span>Close Ticket</span></a></li>
															@endif
														</ul>
													</div>
												</div>
											</li>
										</ul>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/supports/show.blade.php
@extends('layouts.user.app')

@section('title', __('My Ticket'))

@section('theB')
<div class="nk-content p-0"><div class="nk-content-inner">
@endsection

@section('content')
<div class="nk-content-body p-0">
	<div class="nk-msg">
		<div class="nk-msg-body bg-white profile-shown">
			<div class="nk-msg-head">
				<h4 class="title d-none d-lg-block">{{ $support->subject }}</h4>
				<div class="nk-msg-head-meta">
					<div class="d-none d-lg-block">
						<ul class="nk-msg-tags">
							<li><span class="label-tag"><em class="icon ni ni-flag-fill"></em> <span>{{ $support->department }}</span></span></li>
							<li><span class="label-tag"><em class="icon ni ni-circle-fill"></em> <span>{{ $support->priority }}</span></span></li>
						</ul>
					</div>
					<div class="d-lg-none"><a href="#" class="btn btn-icon btn-trigger nk-msg-hide ml-n1"><em class="icon ni ni-arrow-left"></em></a></div>
					<ul class="nk-msg-actions">
						@if($support->status == 'opened')
						<li><a href="/support/close/{{ \Illuminate\Support\Facades\Crypt::encryptString($support->id) }}" class="btn btn-dim btn-sm btn-outline-light"><em class="icon ni ni-check"></em><span>Mark as Closed</span></a></li>
						@endif
						@if($support->status == 'closed')
						<li><span class="badge badge-dim badge-success badge-sm"><em class="icon ni ni-check"></em><span>Closed</span></span></li>
						@endif
						<!--<li class="d-lg-none"><a href="#" class="btn btn-icon btn-sm btn-white btn-light profile-toggle"><em class="icon ni ni-info-i"></em></a></li>-->
					</ul>
				</div>
				<a href="#" class="nk-msg-profile-toggle profile-toggle active"><em class="icon ni ni-arrow-left"></em></a>
			</div>
			<!-- .nk-msg-head -->
			<div class="nk-msg-reply nk-reply" data-simplebar>
				<div class="nk-msg-head py-4 d-lg-none">
					<h4 class="title">{{ $support->subject }}</h4>
					<ul class="nk-msg-tags">
						<li><span class="label-tag"><em class="icon ni ni-flag-fill"></em> <span>{{ $support->department }}</span></span></li>
						<li><span class="label-tag"><em class="icon ni ni-circle-fill"></em> <span>{{ $support->priority }}</span></span></li>
					</ul>
				</div>
				@foreach($support->responses()->latest()->get() as $response)
				<div class="nk-reply-item">
					<div class="nk-reply-header">
						<div class="user-card">
							<div class="user-avatar sm bg-blue">
								@if($response->user->my_details)
									<img src="{{ asset($response->user->my_details->data()->identity->passport) }}">
								@else
									<span>{{ $response->user->nameThumb() }}</span>
								@endif
							</div>
							<div class="user-name">{{ $response->user->getFullname() }}</div>
						</div>
						<div class="date-time">{{ \Carbon\Carbon::createFromTimeStamp(strtotime($response->created_at))->diffForHumans() }}</div>
					</div>
					<div class="nk-reply-body">
						<div class="nk-reply-entry entry">
							{!! $response->response !!}
						</div>
					</div>
				</div>
				@endforeach
				<div class="nk-reply-item">
					<div class="nk-reply-header">
						<div class="user-card">
							<div class="user-avatar sm bg-blue">
								@if($support->user->my_details)
									<img src="{{ asset($support->user->my_details->data()->identity->passport) }}">
								@else
									<span>{{ $support->user->nameThumb() }}</span>
								@endif
							</div>
							<div class="user-name">{{ $support->user->getFullname() }}</div>
						</div>
						<div class="date-time">{{ \Carbon\Carbon::createFromTimeStamp(strtotime($support->created_at))->diffForHumans() }}</div>
					</div>
					<div class="nk-reply-body">
						<div class="nk-reply-entry entry">
							{!! $support->message !!}
						</div>
					</div>
				</div>
				@if($support->status == 'opened')
				<form action="{{ route('supportResponses.store') }}" method="post">
					@csrf
					<input type="hidden" name="support" value="{{ $support->id }}">
					<div class="nk-reply-form">
						<div class="tab-content">
							<div class="tab-pane active" id="reply-form">
								<div class="nk-reply-form-editor">
									<div class="nk-reply-form-field">
										<textarea class="summernote-basic" name="message"></textarea>
										<button type="submit" class="btn btn-lg btn-primary mt-4">Submit</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</form>
				@endif
			</div>
			<!-- .nk-reply -->
			<div class="nk-msg-profile visible" data-simplebar>
				<div class="card">
					<div class="card-inner-group">
						<div class="card-inner">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@push('more-scripts')
<link rel="stylesheet" href="{{ asset('assets/css/editors/summernote.css') }}">
<script src="{{ asset('assets/js/libs/editors/summernote.js') }}"></script>
<script src="{{ asset('assets/js/editors.js') }}"></script>
@endpush