routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\Admin\AdminController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\UserDetailController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\User\LoginLogController;
use App\Http\Controllers\Loan\LoanController;
use App\Http\Controllers\Loan\CreditCheckController;
use App\Http\Controllers\Loan\FolderController;
use App\Http\Controllers\Loan\UploadController;
use App\Http\Controllers\Offer\StatusController;
use App\Http\Controllers\Offer\OfferController;
use App\Http\Controllers\Loan\DefaulterController;
use App\Http\Controllers\Loan\RepaymentController;
use App\Http\Controllers\Loan\CommentController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\SupportResponseController;
use App\Http\Controllers\Report\CustomerBaseController;
use App\Http\Controllers\Report\LoanReportController;
use App\Http\Controllers\Report\LoanProcessController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "is_admin" middleware group. Now create something great!
|
*/

Route::get('/', function(){
	return redirect()->route('admin.home');
});

Route::group(['middleware'=>['is_admin']], function(){
	Route::get('/dashboard', [AdminController::class , 'home'])->name('admin.home');

	Route::resource('users', UserController::class)->except(['edit', 'update']);
	Route::resource('userDetails', UserDetailController::class)->only(['destroy']);
	Route::get('/users/perm/{id}', [UserController::class, 'perm']);
	Route::get('/platform/users/{type}', [UserController::class, 'custom_index']);
	Route::get('/transactions/user/{id}', [TransactionController::class, 'user_transactions']);
	Route::get('/loginLogs/user/{id}', [LoginLogController::class, 'user_login_logs']);

	Route::get('/loans/get/{type}', [LoanController::class, 'custom_index']);
	Route::resource('loans', LoanController::class)->only(['show']);
	Route::get('loans/{action}/{id}', [LoanController::class, 'action']);
	Route::get('loans/return/back/{id}', [LoanController::class, 'returnBack']);
	Route::get('credit_checks/create/{id}', [CreditCheckController::class, 'create_admin']);
	Route::resource('folders', FolderController::class)->only(['index', 'show']);
	Route::get('/folders/create/{id}', [FolderController::class, 'create_admin']);
	Route::get('/folders/show/{id}', [FolderController::class, 'show_main']);
	Route::post('/applications/uploads', [UploadController::class, 'create']);
	Route::resource('uploads', UploadController::class)->only(['destroy']);
	Route::get('/uploads/restore/{id}', [UploadController::class, 'restore']);
	Route::get('/trash', [UploadController::class, 'trash']);
	Route::get('/offers/create/{id}', [OfferController::class, 'createNew']);
	Route::resource('offers', OfferController::class)->only(['edit', 'update', 'show']);
	Route::post('/offers/store', [OfferController::class, 'store'])->name('createOffers');
	Route::get('/payout/loans/{id}', [LoanController::class, 'disburse']);
	Route::get('/defaulters/clear/{id}', [DefaulterController::class, 'clear']);
	Route::get('/repayments/update/user/{id}', [RepaymentController::class, 'updatePayments']);
	Route::resource('repayments', RepaymentController::class);
	Route::get('/comments/create/{id}', [CommentController::class, 'add']);
	Route::resource('comments', CommentController::class)->only(['index', 'store', 'show']);
	Route::resource('referrals', ReferralController::class)->only(['index']);

	Route::get('staff', [UserController::class, 'staff']);
	Route::get('staff/add', [UserController::class, 'new_staff']);
	Route::post('staff/add', [UserController::class, 'new_staff_post']);
	Route::get('staff/edit/{id}', [UserController::class, 'edit']);
	Route::post('staff/edit/{id}', [UserController::class, 'update']);
	Route::resource('transactions', TransactionController::class)->only(['index']);
	Route::resource('supportResponses', SupportResponseController::class)->except(['destroy', 'update', 'edit']);
	Route::get('/support/close/{id}', [SupportResponseController::class, 'closeSupport']);

	Route::get('/reports/customer-base', CustomerBaseController::class);
	Route::get('/reports/customer-base-generate', [CustomerBaseController::class, 'generate']);

	Route::get('/reports/loan-reports', LoanReportController::class);
	Route::get('/reports/loan-reports-generate', [LoanReportController::class, 'generate']);

	Route::get('/reports/loan-process', LoanProcessController::class);
	Route::get('/reports/loan-process-generate', [LoanProcessController::class, 'generate']);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\UserDetailController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\WalletController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\User\ChangePasswordController;
use App\Http\Controllers\User\AccountSecurityController;
use App\Http\Controllers\User\NotificationController;
use App\Http\Controllers\Transaction\CardController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\Loan\LoanController;
use App\Http\Controllers\Loan\CreditCheckController;
use App\Http\Controllers\Loan\RepaymentController;
use App\Http\Controllers\Offer\SignatureController;
use App\Http\Controllers\Offer\OfferController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\SupportResponseController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register'=>false, 'verify'=>true]);
Route::get('/migrate-my-db', function(){
	Artisan::call('migrate:fresh', [
	   '--force' => true, '--seed' => true
	]);
});

Route::group(['middleware'=>['auth','verified','is_user']], function(){
	/**Kyc Routes **/
	Route::get('/application', [UserDetailController::class, 'kyc']);
	Route::get('/application/preview', [UserDetailController::class, 'preview']);
	Route::group(['prefix'=>'application', 'middleware'=>'is_completed'], function() {
		Route::resource('kyc', UserDetailController::class)->only(['create', 'store']);
		Route::resource('pin', AccountSecurityController::class)->only(['create', 'store']);
		Route::get('/card/create', [CardController::class, 'initiateCardLink']);
		Route::get('/card/verify', [CardController::class, 'verifyPayment']);
	});
	/**Kyc Routes ends**/
	Route::group(['middleware'=>'is_complete'], function(){
		Route::get('/dashboard', [UserController::class, 'home'])->name('home');
		Route::resource('transactions', TransactionController::class)->only('index');
		Route::resource('loans', LoanController::class)->except(['edit', 'update']);
		Route::get('/credit-checks', [CreditCheckController::class, 'initiatePayment']);
		Route::get('/credit-checks/create', [CreditCheckController::class, 'create']);
		Route::resource('offers', OfferController::class)->only(['show']);
		Route::get('/loans/offer/sign/{id}', [OfferController::class, 'sign']);
		Route::resource('signatures', SignatureController::class)->only(['store']);
		Route::get('/repayments/from-wallet', [RepaymentController::class, 'payFromWallet']);
		Route::get('/repayments/from-card', [RepaymentController::class, 'initiateCardLink']);
		Route::get('/repayments/from-card/confirm', [RepaymentController::class, 'payFromCardConfirm']);

		Route::get('/profile', [UserController::class, 'profile']);
		Route::get('/security', [UserController::class, 'security']);
		Route::get('/notifications-settings', [UserController::class, 'notificationSetting']);
		Route::post('/notifications-settings', [UserController::class, 'notificationSettingPost'])->name('settings');
		Route::post('/security', [UserController::class, 'securityPost'])->name('secure_setting');
		Route::post('change-password', [ChangePasswordController::class, 'store'])->name('change.password');
		Route::get('/change-password', [ChangePasswordController::class, 'index']);

		Route::resource('referrals', ReferralController::class)->only(['index']);


		Route::group(['prefix'=>'wallet'], function(){
			Route::get('/', [WalletController::class, 'index']);
			Route::get('/deposit', [WalletController::class, 'deposit']);
			Route::post('/deposit', [WalletController::class, 'depositPost']);
			Route::get('/deposit/confirm', [WalletController::class, 'confirmDeposit']);
			Route::get('/withdraw', [WalletController::class, 'withdraw']);
			Route::post('/withdraw', [WalletController::class, 'withdrawPost']);
		});

		Route::resource('supports', SupportController::class)->except(['destroy', 'update', 'edit']);
		Route::resource('supportResponses', SupportResponseController::class)->except(['destroy', 'update', 'edit']);
		Route::get('/support/close/{id}', [SupportController::class, 'closeSupport']);

		Route::group(['prefix'=>'notifications'], function(){
			Route::get('/view/{id}', [NotificationController::class, 'view']);
			Route::get('/read_all', [NotificationController::class, 'read']);
		});

		Route::get('clear-loan/{id}', [LoanController::class, 'clearLoan']);
	});
	
});

Route::group(['middleware'=>'guest'], function(){
	Route::get('/', function(){
		return redirect()->route('home');
	});

	Route::group(['prefix'=>'auth'], function(){
		Route::get('register', [UserController::class, 'create'])->name('user.create');
		Route::post('register', [UserController::class, 'store'])->name('user.create');
	});
});


Route::get('/verify_referee/{ref}', [UserController::class, 'verify_referee'])->name('verify.referee');
Route::get('/charts', [ReferralController::class, 'userChart'])->name('referral.chart');
Route::post('/save-passport', [UserDetailController::class, 'savePassport']);
Route::post('/save-id', [UserDetailController::class, 'saveID']);
Route::post('/save-company-id', [UserDetailController::class, 'saveCompanyID']);
Route::get('/check-uploads', [UserDetailController::class, 'checkUploads']);
Route::get('/check-bvn/{bvn}/{phone}', [UserDetailController::class, 'getBvn']);
Route::get('/check-bank/{bank}/{account}', [UserDetailController::class, 'getBank']);
Route::post('/save-employment-letter', [LoanController::class, 'saveEmployment']);
Route::post('/save-utility-bill', [LoanController::class, 'saveUtility']);
Route::post('/save-statements', [LoanController::class, 'saveStatements']);
Route::post('/pin/validate', [AccountSecurityController::class, 'validatePin']);

app/Http/Controllers/Transaction/CardController.php
<?php

namespace App\Http\Controllers\Transaction;

use App\Http\Requests\Transaction\CardRequest;
use App\Http\Resources\Transaction\CardResource;
use App\Interfaces\Transaction\CardInterface;
use Shamaseen\Repository\Generator\Utility\Controller;

/**
 * Class CardController
 * @package App\Http\Controllers\Transaction
 * @property-read CardInterface $interface
 */
class CardController extends Controller
{

    protected $routeIndex = 'cards';

    protected $pageTitle = 'Card';
    protected $createRoute = 'cards.create';

    protected $viewIndex = 'cards.index';
    protected $viewCreate = 'cards.create';
    protected $viewEdit = 'cards.edit';
    protected $viewShow = 'cards.show';

    /**
     * CardController constructor.
     * @param CardInterface $interface
     * @param CardRequest $request
     * @param CardResource $resource
     */
    public function __construct(CardInterface $interface, CardRequest $request)
    {
        parent::__construct($interface, $request, new  CardResource([]));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->interface->index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return parent::create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        return parent::store();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return parent::show($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return parent::edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id)
    {
        return parent::update($id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        return parent::destroy($id);
    }

    public function initiateCardLink(){
      return $this->interface->initiateCardLink();
    }

    public function verifyPayment(){
      return $this->interface->verifyPayment();
    }

    public function initiateCardAccess()
    {
        return $this->interface->initiateCardAccess();
    }
}

app/Http/Controllers/Transaction/TransactionController.php
<?php

namespace App\Http\Controllers\Transaction;

use App\Http\Requests\Transaction\TransactionRequest;
use App\Http\Resources\Transaction\TransactionResource;
use App\Interfaces\Transaction\TransactionInterface;
use Shamaseen\Repository\Generator\Utility\Controller;

/**
 * Class TransactionController
 * @package App\Http\Controllers\Transaction
 * @property-read TransactionInterface $interface
 */
class TransactionController extends Controller
{

    protected $routeIndex = 'transactions';

    protected $pageTitle = 'Transaction';
    protected $createRoute = 'transactions.create';

    protected $viewIndex = 'transactions.index';
    protected $viewCreate = 'transactions.create';
    protected $viewEdit = 'transactions.edit';
    protected $viewShow = 'transactions.show';

    /**
     * TransactionController constructor.
     * @param TransactionInterface $interface
     * @param TransactionRequest $request
     * @param TransactionResource $resource
     */
    public function __construct(TransactionInterface $interface, TransactionRequest $request)
    {
        parent::__construct($interface, $request, new  TransactionResource([]));
        $this->middleware('role:super admin|coo|risk|director|chairman|transaction officer|user', ['only' => ['index']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
         public function index()*/
    public function index()
    {
        return $this->interface->index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return parent::create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        return parent::store();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return parent::show($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return parent::edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id)
    {
        return parent::update($id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        return parent::destroy($id);
    }


    public function user_transactions($id){
        return $this->interface->user_transactions($id);
    }
}

resources/views/transactions/create.blade.php
@extends('layouts.app')

@section('content')

<form method="post" action="#">
           <input type="hidden" name="__method" value="post">
<div class="form-group">
    <label for="id">Id</label>
    <input type="text" class="form-control" id="id" name="id" value="{{old('id',$entity ? $entity->id : "")}}" required >
</div>
<div class="form-group">
    <label for="user_id">User id</label>
    <input type="text" class="form-control" id="user_id" name="user_id" value="{{old('user_id',$entity ? $entity->user_id : "")}}" required >
</div>
<div class="form-group">
    <label for="details">Details</label>
    <input type="text" class="form-control" id="details" name="details" value="{{old('details',$entity ? $entity->details : "")}}" required >
</div>
<div class="form-group">
    <label for="created_at">Created at</label>
    <input type="text" class="form-control" id="created_at" name="created_at" value="{{old('created_at',$entity ? $entity->created_at : "")}}"  >
</div>
<div class="form-group">
    <label for="updated_at">Updated at</label>
    <input type="text" class="form-control" id="updated_at" name="updated_at" value="{{old('updated_at',$entity ? $entity->updated_at : "")}}"  >
</div>
<div class="form-group">
    <label for="deleted_at">Deleted at</label>
    <input type="text" class="form-control" id="deleted_at" name="deleted_at" value="{{old('deleted_at',$entity ? $entity->deleted_at : "")}}"  >
</div><button type='submit' class='btn btn-primary'>Submit</button></form>

@endsection

resources/views/transactions/edit.blade.php
@extends('layouts.app')

@section('content')

<form method="post" action="#">
           <input type="hidden" name="__method" value="put">
<div class="form-group">
    <label for="id">Id</label>
    <input type="text" class="form-control" id="id" name="id" value="{{old('id',$entity ? $entity->id : "")}}" required >
</div>
<div class="form-group">
    <label for="user_id">User id</label>
    <input type="text" class="form-control" id="user_id" name="user_id" value="{{old('user_id',$entity ? $entity->user_id : "")}}" required >
</div>
<div class="form-group">
    <label for="details">Details</label>
    <input type="text" class="form-control" id="details" name="details" value="{{old('details',$entity ? $entity->details : "")}}" required >
</div>
<div class="form-group">
    <label for="created_at">Created at</label>
    <input type="text" class="form-control" id="created_at" name="created_at" value="{{old('created_at',$entity ? $entity->created_at : "")}}"  >
</div>
<div class="form-group">
    <label for="updated_at">Updated at</label>
    <input type="text" class="form-control" id="updated_at" name="updated_at" value="{{old('updated_at',$entity ? $entity->updated_at : "")}}"  >
</div>
<div class="form-group">
    <label for="deleted_at">Deleted at</label>
    <input type="text" class="form-control" id="deleted_at" name="deleted_at" value="{{old('deleted_at',$entity ? $entity->deleted_at : "")}}"  >
</div><button type='submit' class='btn btn-primary'>Submit</button></form>

@endsection

resources/views/transactions/show.blade.php
@extends('layouts.admin.app')

@section('title', __('Viewing user > User Transactions'))

@section('content')
<div class="nk-content-inner">
	<div class="nk-content-body">
		<div class="nk-block-head nk-block-head-sm">
			<div class="nk-block-between g-3">
				<div class="nk-block-head-content">
					<h3 class="nk-block-title page-title">Users / <strong class="text-primary small">{{ $user->getFullname() }}</strong></h3>
					<div class="nk-block-des text-soft">
						<ul class="list-inline">
							<li>User ID: <span class="text-base">GID{{ str_pad($user->id,6,0,STR_PAD_LEFT) }}</span></li>
							<li>Last Login: @if($user->login_logs()->count() > 0) <span class="text-base">{{ date('d M, Y h:i A', strtotime($user->login_logs()->orderBy('id', 'desc')->skip(1)->first()->created_at ?? $user->login_logs()->orderBy('id', 'desc')->first()->created_at)) }}</span> @endif </li>
						</ul>
					</div>
				</div>
				<div class="nk-block-head-content">
					<a href="{{ url()->previous() }}" class="btn btn-outline-light bg-white d-none d-sm-inline-flex"><em class="icon ni ni-arrow-left"></em><span>Back</span></a>
					<a href="{{ url()->previous() }}" class="btn btn-icon btn-outline-light bg-white d-inline-flex d-sm-none"><em class="icon ni ni-arrow-left"></em></a>
				</div>
			</div>
		</div>
		<!-- .nk-block-head -->
		<div class="nk-block">
			<div class="card">
				<div class="card-aside-wrap">
					<div class="card-content">
						<ul class="nav nav-tabs nav-tabs-mb-icon nav-tabs-card">
							<li class="nav-item">
								<a class="nav-link" href="/users/{{ $user->uuid() }}"><em class="icon ni ni-user-circle"></em><span>Personal</span></a>
							</li>
							<li class="nav-item">
								<a class="nav-link active" href="/transactions/user/{{ $user->uuid() }}"><em class="icon ni ni-repeat"></em><span>Transactions</span></a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="/loginLogs/user/{{ $user->uuid() }}"><em class="icon ni ni-bell"></em><span>Login Logs</span></a>
							</li>
							<li class="nav-item nav-item-trigger d-xxl-none">
								<a href="#" class="toggle btn btn-icon btn-trigger" data-target="userAside"><em class="icon ni ni-user-list-fill"></em></a>
							</li>
						</ul>
						<!-- .nav-tabs -->
						<div class="card-inner">
							<div class="nk-block">
								<div class="nk-block-head">
									<h5 class="title">Transaction</h5>
								</div>
								<table class="datatable-init nk-tb-list nk-tb-ulist" data-auto-responsive="false">
									<thead>
										<tr class="nk-tb-item nk-tb-head">
											<th class="nk-tb-col nk-tb-col-check">
												<div class="custom-control custom-control-sm custom-checkbox notext">
													<input type="checkbox" class="custom-control-input" id="uid">
													<label class="custom-control-label" for="uid"></label>
												</div>
											</th>
											<th class="nk-tb-col"><span class="sub-text">Reference</span></th>
											<th class="nk-tb-col tb-col-mb"><span class="sub-text">Date</span></th>
											<th class="nk-tb-col tb-col-md"><span class="sub-text">Status</span></th>
											<th class="nk-tb-col tb-col-lg"><span class="sub-text">Type</span></th>
											<th class="nk-tb-col tb-col-lg"><span class="sub-text">Description</span></th>
											<th class="nk-tb-col tb-col-md"><span class="sub-text">Amount</span></th>
										</tr>
									</thead>
									<tbody>
										@foreach($user->transactions as $key => $trans)
										<tr class="nk-tb-item">
											<td class="nk-tb-col nk-tb-col-check">
												<div class="custom-control custom-control-sm custom-checkbox notext">
													<input type="checkbox" class="custom-control-input" id="uid{{ $key }}" value="{{ $trans->id }}">
													<label class="custom-control-label" for="uid{{ $key }}"></label>
												</div>
											</td>
											<td class="nk-tb-col">
												<span class="tb-lead"><a href="#">#{{ $trans->data()->reference }}</a></span>
											</td>
											<td class="nk-tb-col tb-col-mb">
												<span class="tb-lead">{{ date('d M, Y h:i A', strtotime($trans->created_at)) }}</span>
											</td>
											<td class="nk-tb-col">{!! $trans->status() !!}</td>
											<td class="nk-tb-col tb-col-md">
												<span class="tb-sub text-primary">{!! $trans->type() !!}</span>
											</td>
											<td class="nk-tb-col tb-col-sm">
												<span class="tb-sub">{{ $trans->data()->description }}</span>
											</td>
											<td class="nk-tb-col tb-col-sm">
												<span class="tb-lead">₦{{ number_format($trans->data()->amount,2) }}</span>
											</td>
										</tr>
										@endforeach
									</tbody>
								</table>
							</div>
							<div class="nk-divider divider md"></div>
						</div>
						<!-- .card-inner -->
					</div>
					<div class="card-aside card-aside-right user-aside toggle-slide toggle-slide-right toggle-break-xxl" data-content="userAside" data-toggle-screen="xxl" data-toggle-overlay="true" data-toggle-body="true">
						<div class="card-inner-group" data-simplebar>
							<div class="card-inner">
								<div class="user-card user-card-s2">
									<div class="user-avatar lg bg-primary">
										@if($details) <img src="{{ asset($details->data()->identity->passport) }}"> @else <span>{{ $user->nameThumb() }}</span>  @endif
									</div>
									<div class="user-info">
										<div class="badge badge-outline-light badge-pill ucap">Customer</div>
										<h5>{{ $user->getFullname() }}</h5>
										<span class="sub-text">{{ $user->email }}</span>
									</div>
								</div>
							</div>
							<!-- .card-inner -->
							<div class="card-inner card-inner-sm">
								<ul class="btn-toolbar justify-center gx-1">
									@if($user->active)
									<li><a href="/users/perm/{{ $user->uuid() }}" class="btn btn-trigger btn-icon text-danger miAction"><em class="icon ni ni-na"></em></a></li>
									@else
									<li><a href="/users/perm/{{ $user->uuid() }}" class="btn btn-trigger btn-icon text-success miAction"><em class="icon ni ni-check-thick"></em></a></li>
									@endif
									@if($user->my_details)
									<li><a href="#" class="btn btn-trigger btn-icon text-success deleteAction" data-target="#delete-kyc{{$user->my_details->id}}"><em class="icon ni ni-edit"></em></a></li>
									<form id="delete-kyc{{$user->my_details->id}}" action="{{ route('userDetails.destroy', $user->my_details->id) }}" method="POST" class="d-none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
									@endif
								</ul>
							</div>
							<div class="card-inner">
								<div class="overline-title-alt mb-2">In Account</div>
								<div class="profile-balance">
									<div class="profile-balance-group gx-4">
										<div class="profile-balance-sub">
											<div class="profile-balance-amount">
												<div class="number">{{ number_format($user->wallet->amount,2) }}<small class="currency currency-usd">NGN</small></div>
											</div>
											<div class="profile-balance-subtitle">Amount in wallet</div>
										</div>
										<div class="profile-balance-sub">
											<span class="profile-balance-plus text-soft"><em class="icon ni ni-plus"></em></span>
											<div class="profile-balance-amount">
												<div class="number">{{ number_format($user->transactions()->where('details->type_for', 'earnings')->orWhere('details->type_for', 'profits')->sum('details->amount'), 2) }}</div>
											</div>
											<div class="profile-balance-subtitle">Profit Earned</div>
										</div>
									</div>
								</div>
							</div>
							<!-- .card-inner -->
							<div class="card-inner">
								<div class="row text-center">
									<div class="col-4">
										<div class="profile-stats">
											<span class="amount">{{ $user->loans()->count() }}</span>
											<span class="sub-text">Total Loans</span>
										</div>
									</div>
									<div class="col-4">
										<div class="profile-stats">
											<span class="amount">{{ $user->loans()->whereHas('status', function ($query) { $query->where('status', 'approved');})->count() }}</span>
											<span class="sub-text">Approved Loans</span>
										</div>
									</div>
									<div class="col-4">
										<div class="profile-stats">
											<span class="amount">{{ $user->loans()->whereHas('status', function ($query) { $query->where('status', 'repaid');})->count() }}</span>
											<span class="sub-text">Cleared Loans</span>
										</div>
									</div>
								</div>
							</div>
							<!-- .card-inner -->
							<div class="card-inner">
								<h6 class="overline-title-alt mb-2">Additional</h6>
								<div class="row g-3">
									<div class="col-6">
										<span class="sub-text">User ID:</span>
										<span>GID{{ str_pad($user->id,6,0,STR_PAD_LEFT) }}</span>
									</div>
									<div class="col-6">
										<span class="sub-text">Last Login:</span>
										<span>@if($user->login_logs()->count() > 0) {{ date('d M, Y h:i A', strtotime($user->login_logs()->orderBy('id', 'desc')->skip(1)->first()->created_at ?? $user->login_logs()->orderBy('id', 'desc')->first()->created_at)) }} @endif</span>
									</div>
									<div class="col-6">
										<span class="sub-text">KYC Status:</span>
										@if($details)
										<span class="lead-text text-success">Approved</span>
										@else
										<span class="lead-text text-info">No KYC found</span>
										@endif
									</div>
									<div class="col-6">
										<span class="sub-text">Register At:</span>
										<span>{{ date('M d, Y', strtotime($user->created_at)) }}</span>
									</div>
								</div>
							</div>
						</div>
						<!-- .card-inner -->
					</div>
					<!-- .card-aside -->
				</div>
				<!-- .card-aside-wrap -->
			</div>
			<!-- .card -->
		</div>
		<!-- .nk-block -->
	</div>
</div>
@endsection