routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\Admin\AdminController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\UserDetailController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\User\LoginLogController;
use App\Http\Controllers\Loan\LoanController;
use App\Http\Controllers\Loan\CreditCheckController;
use App\Http\Controllers\Loan\FolderController;
use App\Http\Controllers\Loan\UploadController;
use App\Http\Controllers\Offer\StatusController;
use App\Http\Controllers\Offer\OfferController;
use App\Http\Controllers\Loan\DefaulterController;
use App\Http\Controllers\Loan\RepaymentController;
use App\Http\Controllers\Loan\CommentController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\SupportResponseController;
use App\Http\Controllers\Report\CustomerBaseController;
use App\Http\Controllers\Report\LoanReportController;
use App\Http\Controllers\Report\LoanProcessController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "is_admin" middleware group. Now create something great!
|
*/

Route::get('/', function(){
	return redirect()->route('admin.home');
});

Route::group(['middleware'=>['is_admin']], function(){
	Route::get('/dashboard', [AdminController::class , 'home'])->name('admin.home');

	Route::resource('users', UserController::class)->except(['edit', 'update']);
	Route::resource('userDetails', UserDetailController::class)->only(['destroy']);
	Route::get('/users/perm/{id}', [UserController::class, 'perm']);
	Route::get('/platform/users/{type}', [UserController::class, 'custom_index']);
	Route::get('/transactions/user/{id}', [TransactionController::class, 'user_transactions']);
	Route::get('/loginLogs/user/{id}', [LoginLogController::class, 'user_login_logs']);

	Route::get('/loans/get/{type}', [LoanController::class, 'custom_index']);
	Route::resource('loans', LoanController::class)->only(['show']);
	Route::get('loans/{action}/{id}', [LoanController::class, 'action']);
	Route::get('loans/return/back/{id}', [LoanController::class, 'returnBack']);
	Route::get('credit_checks/create/{id}', [CreditCheckController::class, 'create_admin']);
	Route::resource('folders', FolderController::class)->only(['index', 'show']);
	Route::get('/folders/create/{id}', [FolderController::class, 'create_admin']);
	Route::get('/folders/show/{id}', [FolderController::class, 'show_main']);
	Route::post('/applications/uploads', [UploadController::class, 'create']);
	Route::resource('uploads', UploadController::class)->only(['destroy']);
	Route::get('/uploads/restore/{id}', [UploadController::class, 'restore']);
	Route::get('/trash', [UploadController::class, 'trash']);
	Route::get('/offers/create/{id}', [OfferController::class, 'createNew']);
	Route::resource('offers', OfferController::class)->only(['edit', 'update', 'show']);
	Route::post('/offers/store', [OfferController::class, 'store'])->name('createOffers');
	Route::get('/payout/loans/{id}', [LoanController::class, 'disburse']);
	Route::get('/defaulters/clear/{id}', [DefaulterController::class, 'clear']);
	Route::get('/repayments/update/user/{id}', [RepaymentController::class, 'updatePayments']);
	Route::resource('repayments', RepaymentController::class);
	Route::get('/comments/create/{id}', [CommentController::class, 'add']);
	Route::resource('comments', CommentController::class)->only(['index', 'store', 'show']);
	Route::resource('referrals', ReferralController::class)->only(['index']);

	Route::get('staff', [UserController::class, 'staff']);
	Route::get('staff/add', [UserController::class, 'new_staff']);
	Route::post('staff/add', [UserController::class, 'new_staff_post']);
	Route::get('staff/edit/{id}', [UserController::class, 'edit']);
	Route::post('staff/edit/{id}', [UserController::class, 'update']);
	Route::resource('transactions', TransactionController::class)->only(['index']);
	Route::resource('supportResponses', SupportResponseController::class)->except(['destroy', 'update', 'edit']);
	Route::get('/support/close/{id}', [SupportResponseController::class, 'closeSupport']);

	Route::get('/reports/customer-base', CustomerBaseController::class);
	Route::get('/reports/customer-base-generate', [CustomerBaseController::class, 'generate']);

	Route::get('/reports/loan-reports', LoanReportController::class);
	Route::get('/reports/loan-reports-generate', [LoanReportController::class, 'generate']);

	Route::get('/reports/loan-process', LoanProcessController::class);
	Route::get('/reports/loan-process-generate', [LoanProcessController::class, 'generate']);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\UserDetailController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\WalletController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\User\ChangePasswordController;
use App\Http\Controllers\User\AccountSecurityController;
use App\Http\Controllers\User\NotificationController;
use App\Http\Controllers\Transaction\CardController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\Loan\LoanController;
use App\Http\Controllers\Loan\CreditCheckController;
use App\Http\Controllers\Loan\RepaymentController;
use App\Http\Controllers\Offer\SignatureController;
use App\Http\Controllers\Offer\OfferController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\SupportResponseController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register'=>false, 'verify'=>true]);
Route::get('/migrate-my-db', function(){
	Artisan::call('migrate:fresh', [
	   '--force' => true, '--seed' => true
	]);
});

Route::group(['middleware'=>['auth','verified','is_user']], function(){
	/**Kyc Routes **/
	Route::get('/application', [UserDetailController::class, 'kyc']);
	Route::get('/application/preview', [UserDetailController::class, 'preview']);
	Route::group(['prefix'=>'application', 'middleware'=>'is_completed'], function() {
		Route::resource('kyc', UserDetailController::class)->only(['create', 'store']);
		Route::resource('pin', AccountSecurityController::class)->only(['create', 'store']);
		Route::get('/card/create', [CardController::class, 'initiateCardLink']);
		Route::get('/card/verify', [CardController::class, 'verifyPayment']);
	});
	/**Kyc Routes ends**/
	Route::group(['middleware'=>'is_complete'], function(){
		Route::get('/dashboard', [UserController::class, 'home'])->name('home');
		Route::resource('transactions', TransactionController::class)->only('index');
		Route::resource('loans', LoanController::class)->except(['edit', 'update']);
		Route::get('/credit-checks', [CreditCheckController::class, 'initiatePayment']);
		Route::get('/credit-checks/create', [CreditCheckController::class, 'create']);
		Route::resource('offers', OfferController::class)->only(['show']);
		Route::get('/loans/offer/sign/{id}', [OfferController::class, 'sign']);
		Route::resource('signatures', SignatureController::class)->only(['store']);
		Route::get('/repayments/from-wallet', [RepaymentController::class, 'payFromWallet']);
		Route::get('/repayments/from-card', [RepaymentController::class, 'initiateCardLink']);
		Route::get('/repayments/from-card/confirm', [RepaymentController::class, 'payFromCardConfirm']);

		Route::get('/profile', [UserController::class, 'profile']);
		Route::get('/security', [UserController::class, 'security']);
		Route::get('/notifications-settings', [UserController::class, 'notificationSetting']);
		Route::post('/notifications-settings', [UserController::class, 'notificationSettingPost'])->name('settings');
		Route::post('/security', [UserController::class, 'securityPost'])->name('secure_setting');
		Route::post('change-password', [ChangePasswordController::class, 'store'])->name('change.password');
		Route::get('/change-password', [ChangePasswordController::class, 'index']);

		Route::resource('referrals', ReferralController::class)->only(['index']);


		Route::group(['prefix'=>'wallet'], function(){
			Route::get('/', [WalletController::class, 'index']);
			Route::get('/deposit', [WalletController::class, 'deposit']);
			Route::post('/deposit', [WalletController::class, 'depositPost']);
			Route::get('/deposit/confirm', [WalletController::class, 'confirmDeposit']);
			Route::get('/withdraw', [WalletController::class, 'withdraw']);
			Route::post('/withdraw', [WalletController::class, 'withdrawPost']);
		});

		Route::resource('supports', SupportController::class)->except(['destroy', 'update', 'edit']);
		Route::resource('supportResponses', SupportResponseController::class)->except(['destroy', 'update', 'edit']);
		Route::get('/support/close/{id}', [SupportController::class, 'closeSupport']);

		Route::group(['prefix'=>'notifications'], function(){
			Route::get('/view/{id}', [NotificationController::class, 'view']);
			Route::get('/read_all', [NotificationController::class, 'read']);
		});

		Route::get('clear-loan/{id}', [LoanController::class, 'clearLoan']);
	});
	
});

Route::group(['middleware'=>'guest'], function(){
	Route::get('/', function(){
		return redirect()->route('home');
	});

	Route::group(['prefix'=>'auth'], function(){
		Route::get('register', [UserController::class, 'create'])->name('user.create');
		Route::post('register', [UserController::class, 'store'])->name('user.create');
	});
});


Route::get('/verify_referee/{ref}', [UserController::class, 'verify_referee'])->name('verify.referee');
Route::get('/charts', [ReferralController::class, 'userChart'])->name('referral.chart');
Route::post('/save-passport', [UserDetailController::class, 'savePassport']);
Route::post('/save-id', [UserDetailController::class, 'saveID']);
Route::post('/save-company-id', [UserDetailController::class, 'saveCompanyID']);
Route::get('/check-uploads', [UserDetailController::class, 'checkUploads']);
Route::get('/check-bvn/{bvn}/{phone}', [UserDetailController::class, 'getBvn']);
Route::get('/check-bank/{bank}/{account}', [UserDetailController::class, 'getBank']);
Route::post('/save-employment-letter', [LoanController::class, 'saveEmployment']);
Route::post('/save-utility-bill', [LoanController::class, 'saveUtility']);
Route::post('/save-statements', [LoanController::class, 'saveStatements']);
Route::post('/pin/validate', [AccountSecurityController::class, 'validatePin']);

app/Http/Controllers/Offer/OfferController.php
<?php

namespace App\Http\Controllers\Offer;

use App\Http\Requests\Offer\OfferRequest;
use App\Http\Resources\Offer\OfferResource;
use App\Interfaces\Offer\OfferInterface;
use Shamaseen\Repository\Generator\Utility\Controller;
use Illuminate\Support\Facades\Crypt;

/**
 * Class OfferController
 * @package App\Http\Controllers\Offer
 * @property-read OfferInterface $interface
 */
class OfferController extends Controller
{

    protected $routeIndex = 'offers';

    protected $pageTitle = 'Offer';
    protected $createRoute = 'offers.create';

    protected $viewIndex = 'offers.index';
    protected $viewCreate = 'offers.create';
    protected $viewEdit = 'offers.edit';
    protected $viewShow = 'offers.show';

    /**
     * OfferController constructor.
     * @param OfferInterface $interface
     * @param OfferRequest $request
     * @param OfferResource $resource
     */
    public function __construct(OfferInterface $interface, OfferRequest $request)
    {
        parent::__construct($interface, $request, new  OfferResource([]));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return parent::index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return parent::create();
    }

    public function createNew($id)
    {
        return $this->interface->createNew($id);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        return $this->interface->store();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $this->interface->show($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->interface->edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id)
    {
        return $this->interface->update($id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        return parent::destroy($id);
    }

    public function sign($id){
        return $this->interface->sign($id);
    }
}

app/Http/Controllers/Offer/SignatureController.php
<?php

namespace App\Http\Controllers\Offer;

use App\Http\Requests\Offer\SignatureRequest;
use App\Http\Resources\Offer\SignatureResource;
use App\Interfaces\Offer\SignatureInterface;
use Shamaseen\Repository\Generator\Utility\Controller;

/**
 * Class SignatureController
 * @package App\Http\Controllers\Offer
 * @property-read SignatureInterface $interface
 */
class SignatureController extends Controller
{

    protected $routeIndex = 'signatures';

    protected $pageTitle = 'Signature';
    protected $createRoute = 'signatures.create';

    protected $viewIndex = 'signatures.index';
    protected $viewCreate = 'signatures.create';
    protected $viewEdit = 'signatures.edit';
    protected $viewShow = 'signatures.show';

    /**
     * SignatureController constructor.
     * @param SignatureInterface $interface
     * @param SignatureRequest $request
     * @param SignatureResource $resource
     */
    public function __construct(SignatureInterface $interface, SignatureRequest $request)
    {
        parent::__construct($interface, $request, new  SignatureResource([]));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return parent::index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return parent::create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        return $this->interface->store();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return parent::show($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return parent::edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id)
    {
        return parent::update($id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        return parent::destroy($id);
    }

}

resources/views/offers/edit.blade.php
@php
use App\Http\Controllers\GlobalMethods as SuperM;
@endphp

@extends('layouts.admin.app')

@section('title', __('Edit Offer Letter'))

@push('more-scripts')
<link rel="stylesheet" href="{{ asset('assets/css/editors/summernote.css') }}">
<script src="{{ asset('assets/js/libs/editors/summernote.js') }}"></script>
<script src="{{ asset('assets/js/editors.js') }}"></script>
@endpush

@section('content')
<div class="nk-content-inner">
    <div class="nk-content-body">
        <div class="components-preview wide-md mx-auto">
            <div class="nk-block-head nk-block-head-lg wide-sm">
                <div class="nk-block-head-content">
                    <div class="nk-block-head-sub"><a class="back-to" href="{{ url()->previous() }}"><em class="icon ni ni-arrow-left"></em><span>Back</span></a></div>
                    <h2 class="nk-block-title fw-normal">Create Offer Letter</h2>
                </div>
            </div>
            <!-- nk-block -->
            <div class="nk-block nk-block-lg">
                <div class="card card-preview">
                    <div class="card-inner">
                        <div class="nk-upload-form">
                            <h5 class="title mb-3">Create Offer</h5>
                            <form method="post" action="{{ route('offers.update', $entity->id) }}">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Facility Type</label>
                                        <input type="text" class="form-control" name="facility_type" value="{{ strtoupper($entity->data()->facility_type) }}">
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Amount</label>
                                        <input type="number" class="form-control" name="amount" value="{{ $entity->data()->amount }}">
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Mode of Disbursement</label>
                                        <input type="text" class="form-control" name="mode_of_disbursement" value="Bank Transfer" value="{{ $entity->data()->mode_of_disbursement }}">
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Repayment Source</label>
                                        <input type="text" class="form-control" name="repayment_source" value="{{ $entity->data()->repayment_source }}">
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Interest</label>
                                        <input type="number" class="form-control" name="interest" value="{{ $entity->data()->interest }}">
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Processing Fee</label>
                                        <input type="number" class="form-control" name="processing" value="{{ $entity->data()->processing }}">
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Management Fee</label>
                                        <input type="number" class="form-control" name="management" value="{{ $entity->data()->management }}">
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Outstanding balance</label>
                                        <input type="number" class="form-control" name="outstanding" value="0" step="any" value="{{ $entity->data()->outstanding }}">
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Tenor</label>
                                        <select class="form-control" name="tenor">
                                           @for($i=3;$i<25;$i++)
                                           <option value="{{ $i }}" {{ $entity->data()->tenor == $i ? 'checked':'' }}>{{ $i }} months</option>
                                           @endfor 
                                        </select>
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Moratorium</label>
                                        <input type="number" class="form-control" name="moratorium" value="{{ $entity->data()->moratorium }}">
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Pay Date</label>
                                        <input type="number" class="form-control" name="pay_date" value="{{ $entity->data()->pay_date }}">
                                    </div>
                                    <div class="form-group col-xl-3 col-lg-4 col-md-6">
                                        <label>Payment Starts</label>
                                        <select class="form-control" name="payment_starts">
                                            <option value="this" {{ $entity->data()->payment_starts == 'this' ? 'checked':'' }}>This month</option>
                                            <option value="next" {{ $entity->data()->payment_starts == 'next' ? 'checked':'' }}>Next Month</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-12">
                                        <label>CONDITION PRECEDENT TO DRAWDOWN</label>
                                        <textarea class="summernote-minimal" name="condition_precedent_to_dropdown">
                                            {!! $entity->data()->condition_precedent_to_dropdown !!}
                                        </textarea>
                                    </div>
                                    <div class="form-group col-12">
                                        <label>OTHER CONDITIONS</label>
                                        <textarea class="summernote-minimal" name="other_conditions">
                                            {!! $entity->data()->other_conditions !!}
                                        </textarea>
                                    </div>
                                    <div class="form-group col-12">
                                        <label>EVENTS OF DEFAULT</label>
                                        <textarea class="summernote-minimal" name="event_of_defaults">
                                            {!! $entity->data()->event_of_defaults !!}
                                        </textarea>
                                    </div>
                                </div>
                                <button class="btn btn-primary mt-4" type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/offers/index.blade.php
@extends('layouts.app')

@section('content')

@endsection

resources/views/offers/previewer.blade.php
<!DOCTYPE html>
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <title>Glaze Credit File viewer</title>
        <style type="text/css">
            body {
                background: #000;
                position: absolute;
                top: 0;
                bottom: 0;left: 0;
                right: 0;
            }
            iframe {
                width: 80%;
                margin-right: 10%;
                margin-left: 10%;
                min-height: 90%;
                margin-top: 5%;
                margin-bottom: 5%;
                background: #0EAC81;
            }
            .headert {
                background: #0EAC81;
                position: fixed;
                top: 0;
                left: 0;
                right: 0;
                padding: 15px 15px;
            }
            .headert img {
                width: 160px;
            }
        </style>
    </head>
    <body>
        <div class="headert">
            <a href="/"><img src="{{ asset('logo_icon.png') }}" width="120"> </a>
        </div>
        <iframe src="{{ $file }}" frameborder="0" seamless></iframe>
    </body>
</html>

resources/views/offers/sign.blade.php
<!DOCTYPE html>
<html lang="zxx" class="js">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Sign Your offer | Glaze Credit</title>
        <link rel="stylesheet" href="{{ asset('admin_assets/assets/css/dashlite.css') }}">
        <link id="skin-default" rel="stylesheet" href="{{ asset('admin_assets/assets/css/skins/theme-green.css') }}">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <!--[if IE]> 
        <script type="text/javascript" src="{{ asset('assets/signature/js/excanvas.js') }}"></script> 
        <![endif]-->
        <script type="text/javascript" src="{{ asset('assets/signature/js/jquery.ui.touch-punch.min.js') }}"></script> 
        <link type="text/css" href="{{ asset('assets/signature/css/jquery.signature.css') }}" rel="stylesheet"> 
        <script type="text/javascript" src="{{ asset('assets/signature/js/jquery.signature.js') }}"></script>
        <style>
        .kbw-signature { width: 400px; height: 200px; }
        </style>
        <script type="text/javascript">
          $(function() {
              //alert('done');
            var sig = $('#sig').signature();
            var sig2 = $('#sig2').signature();
            
            $('#clear').click(function() {
              sig.signature('clear');
            });
            $('#clear2').click(function() {
              sig2.signature('clear');
            });
            $('#svg').click(function() {
              alert(sig.signature('toSVG'));
            });
            $('#dSub').click(function() {
              $('#dsvgs').html(sig.signature('toSVG')+sig2.signature('toSVG'));
              var svg = document.getElementsByTagName("svg")[0];
              var bbox = svg.getBBox();
              var viewBox = [bbox.x, bbox.y, bbox.width, bbox.height].join(" ");
              svg.setAttribute("viewBox", viewBox);
              // second svg
              var svg2 = document.getElementsByTagName("svg")[1];
              var bbox2 = svg2.getBBox();
              var viewBox2 = [bbox2.x, bbox2.y, bbox2.width, bbox2.height].join(" ");
              svg2.setAttribute("viewBox", viewBox2);

              $('input[name=signature]').val(svg.outerHTML);
              $('input[name=signature2]').val(svg2.outerHTML);
              $('#d_form').submit();
            });
          });
        </script>
    </head>
    <body class="nk-body bg-lighter npc-default has-sidebar ">
      <div class="container">
        <div class="row">
            <div class="col-lg-12">
              @if(session()->has('message'))
                      {!! session()->get('message') !!}
                  @endif
                <div class="card">
                  <form action="{{ route('signatures.store') }}" method="post" id="d_form">
                    @csrf
                    <input type="hidden" name="loan" value="{{ $loan->id }}">
                      <div class="card-body">
                        <div class="row">
                          <div class="col-12">
                            <div class="card">
                              <div class="card-body">
                                <div class="jumbotron mb-0 bg-light">
                                  <h3 class="display-6">Hello {{ ucwords($loan->user->first_name.' '.$loan->user->last_name) }}</h3>
                                  <p class="lead">Please click the button below to preview, download and confirm your offer letter.</p>
                                  <hr class="my-4">
                                  <p>
                                    After previewing your offer, please append your signature below and click the submit button so as to proceed with your loan processing.
                                  </p>
                                  <p>
                                    Please ignore if you do not accept the offer given to you and contact your account officer for guidance.
                                  </p>
                                  <a class="btn btn-primary btn-lg" target="_blank" href="/offers/{{ $offer->uuid() }}" role="button">Preview Offer</a>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="col-lg-6 text-center">
                            <h4 class="card-title">Signature</h4>
                        <div id="sig"></div>
                        <input type="hidden" name="signature" required="">
                      <p style="clear: both;">
                        <button type="button" class="btn btn-warning btn-sm" id="clear">Clear</button> 
                      </p>
                      </div>
                      <div class="col-lg-6 text-center">
                            <h4 class="card-title">Confirm Signature</h4>
                        <div id="sig2"></div>
                        <input type="hidden" name="signature2" required="">
                      <p style="clear: both;">
                        <button type="button" class="btn btn-warning btn-sm" id="clear2">Clear</button> 
                      </p>
                      </div>
                      
                      <div class="col-lg-12 mt-3">
                        <button id="dSub" type="button" class="btn btn-lg btn-block btn-primary">SUBMIT</button>
                      </div>
                      <div id="dsvgs"></div>
                        </div>
                      </div>
                  </form>
                </div>
            </div>
        </div>
      </div>
    </body>
</html>